"""Sufficiency observation core — public contract surface."""

from offline_rag.sufficiency.artifacts import (
    SUFFICIENCY_EVAL_CONTEXT_MANIFEST_V1,
    SUFFICIENCY_EVAL_CONTEXT_V1,
    SUFFICIENCY_FAILURE_RECORD_V1,
    SufficiencyArtifactError,
    SufficiencyAttemptGroupV1,
    SufficiencyAttemptRefV1,
    SufficiencyEvalContextManifestV1,
    SufficiencyEvalContextSnapshotV1,
    SufficiencyFailureRecordV1,
    SufficiencyManifestAuditV1,
    SufficiencySharedLineageV1,
    SufficiencySnapshotAuditV1,
    build_failure_record,
    build_sufficiency_manifest,
    build_sufficiency_snapshot,
    require_authoritative_manifest,
    shared_lineage_from_provenance,
    validate_sufficiency_manifest,
    validate_sufficiency_snapshot,
)
from offline_rag.sufficiency.config_hash import build_observation_config_hash
from offline_rag.sufficiency.contracts import (
    SUFFICIENCY_OBSERVATION_V1,
    SUFFICIENCY_PROVENANCE_V1,
    SufficiencyDerivationError,
    SufficiencyError,
    SufficiencyErrorCodeV1,
    SufficiencyErrorDetailsV1,
    SufficiencyObservationV1,
    SufficiencyProvenanceV1,
    SufficiencyValidationError,
)
from offline_rag.sufficiency.derive import (
    derive_sufficiency_observation,
    validate_observation_against_provenance,
)
from offline_rag.sufficiency.ids import build_suffctx_id, build_suffctxrun_id
from offline_rag.sufficiency.persist import (
    SufficiencyPersistenceError,
    default_manifest_artifact_path,
    default_snapshot_artifact_path,
    load_sufficiency_manifest,
    load_sufficiency_snapshot,
    persist_sufficiency_manifest,
    persist_sufficiency_snapshot,
)
from offline_rag.sufficiency.policy import (
    EMPTY_CONTEXT_GATE,
    SUFFICIENCY_POLICY_V1,
    SufficiencyPolicyDecisionV1,
    SufficiencyPolicyError,
    decision_diagnostics,
    evaluate_runtime_sufficiency,
    evaluate_sufficiency_policy_v1,
    require_runtime_sufficiency_policy,
)

__all__ = [
    "EMPTY_CONTEXT_GATE",
    "SUFFICIENCY_EVAL_CONTEXT_MANIFEST_V1",
    "SUFFICIENCY_EVAL_CONTEXT_V1",
    "SUFFICIENCY_FAILURE_RECORD_V1",
    "SUFFICIENCY_OBSERVATION_V1",
    "SUFFICIENCY_POLICY_V1",
    "SUFFICIENCY_PROVENANCE_V1",
    "SufficiencyArtifactError",
    "SufficiencyAttemptGroupV1",
    "SufficiencyAttemptRefV1",
    "SufficiencyDerivationError",
    "SufficiencyError",
    "SufficiencyErrorCodeV1",
    "SufficiencyErrorDetailsV1",
    "SufficiencyEvalContextManifestV1",
    "SufficiencyEvalContextSnapshotV1",
    "SufficiencyFailureRecordV1",
    "SufficiencyManifestAuditV1",
    "SufficiencyObservationV1",
    "SufficiencyPersistenceError",
    "SufficiencyPolicyDecisionV1",
    "SufficiencyPolicyError",
    "SufficiencyProvenanceV1",
    "SufficiencySharedLineageV1",
    "SufficiencySnapshotAuditV1",
    "SufficiencyValidationError",
    "build_failure_record",
    "build_observation_config_hash",
    "build_suffctx_id",
    "build_suffctxrun_id",
    "build_sufficiency_manifest",
    "build_sufficiency_snapshot",
    "decision_diagnostics",
    "default_manifest_artifact_path",
    "default_snapshot_artifact_path",
    "derive_sufficiency_observation",
    "evaluate_runtime_sufficiency",
    "evaluate_sufficiency_policy_v1",
    "load_sufficiency_manifest",
    "load_sufficiency_snapshot",
    "persist_sufficiency_manifest",
    "persist_sufficiency_snapshot",
    "require_authoritative_manifest",
    "require_runtime_sufficiency_policy",
    "shared_lineage_from_provenance",
    "validate_observation_against_provenance",
    "validate_sufficiency_manifest",
    "validate_sufficiency_snapshot",
]
