"""Code-owned Slice 7 semantic contract identifiers."""

from __future__ import annotations

from offline_rag.core.ids import (
    ANCHOR_PRESERVING_CLIP_V1,
    FIRST_ANCHOR_OWNS_V1,
    NEIGHBOR_WINDOW_V1,
    PLAIN_EVIDENCE_V1,
    RANK_PRIORITY_HARD_BUDGET_V1,
    SUPPRESS_CONTAINED_CHILDREN_V1,
    TIKTOKEN_TOKENIZER_CONTRACT,
)

ASSEMBLY_CONTRACT = RANK_PRIORITY_HARD_BUDGET_V1
CLIP_CONTRACT = ANCHOR_PRESERVING_CLIP_V1
DEDUP_CONTRACT = FIRST_ANCHOR_OWNS_V1
CONTAINMENT_CONTRACT = SUPPRESS_CONTAINED_CHILDREN_V1
NEIGHBOR_CONTRACT = NEIGHBOR_WINDOW_V1
RENDER_CONTRACT = PLAIN_EVIDENCE_V1
TOKEN_COUNTER_CONTRACT = TIKTOKEN_TOKENIZER_CONTRACT

STOP_COMPLETED = "completed"
STOP_BUDGET_EXHAUSTED = "budget_exhausted"
STOP_CHILD_WOULD_NOT_FIT = "child_would_not_fit"
STOP_PARENT_CLIPPED_TO_BUDGET = "parent_clipped_to_budget"
STOP_NO_ANCHORS = "no_anchors"
STOP_ANCHOR_WOULD_NOT_FIT = "anchor_would_not_fit"
