"""Project-owned domain schemas.

These models must remain free of Docling, Qdrant, LangChain, Ollama, or other
infrastructure types. Adapters translate external objects into these contracts.
"""

from offline_rag.domain.blocks import (
    ContentBlock,
    ContentType,
    ParsedDocument,
    ParseWarning,
    SourceLocator,
    WarningCategory,
)
from offline_rag.domain.chunking import (
    ChunkingReport,
    ChunkingStatus,
    ChunkSetDocumentEntry,
    ChunkSetManifest,
    ChunkState,
    DocumentChunkArtifact,
    DocumentChunkResult,
    DocumentChunkStatus,
)
from offline_rag.domain.corpus import (
    CorpusDocumentEntry,
    CorpusManifest,
    CorpusSourceEntry,
    CorpusState,
)
from offline_rag.domain.documents import Chunk, ChunkKind, Document
from offline_rag.domain.evaluation import EvaluationResult, ExperimentConfig
from offline_rag.domain.generation import Citation
from offline_rag.domain.indexing import (
    DenseCandidate,
    DenseIndexManifest,
    DenseRetrievalEvaluationResult,
    DenseRetrievalResult,
    DocumentIndexStatus,
    EmbeddingArtifact,
    EmbeddingModelManifest,
    EmbeddingProvisionReport,
    FusionProvenance,
    HybridCandidate,
    HybridRetrievalEvaluationResult,
    HybridRetrievalResult,
    IndexingReport,
    IndexingStatus,
    IndexState,
    LexicalCandidate,
    LexicalIndexingReport,
    LexicalIndexManifest,
    LexicalIndexState,
    LexicalRetrievalEvaluationResult,
    LexicalRetrievalResult,
    ProvisioningStatus,
    RetrievalCaseResult,
    RetrievalEvalCase,
    RetrievalEvalDatasetMeta,
)
from offline_rag.domain.ingestion import (
    FileIngestionResult,
    FileIngestionStatus,
    IngestionReport,
    IngestionStatus,
)
from offline_rag.domain.retrieval import RetrievalCandidate, RetrievalResult
from offline_rag.domain.traces import QueryTrace

__all__ = [
    "Chunk",
    "ChunkKind",
    "ChunkSetDocumentEntry",
    "ChunkSetManifest",
    "ChunkState",
    "ChunkingReport",
    "ChunkingStatus",
    "Citation",
    "ContentBlock",
    "ContentType",
    "CorpusDocumentEntry",
    "CorpusManifest",
    "CorpusSourceEntry",
    "CorpusState",
    "DenseCandidate",
    "DenseIndexManifest",
    "DenseRetrievalEvaluationResult",
    "DenseRetrievalResult",
    "Document",
    "DocumentChunkArtifact",
    "DocumentChunkResult",
    "DocumentChunkStatus",
    "DocumentIndexStatus",
    "EmbeddingArtifact",
    "EmbeddingModelManifest",
    "EmbeddingProvisionReport",
    "EvaluationResult",
    "ExperimentConfig",
    "FileIngestionResult",
    "FileIngestionStatus",
    "FusionProvenance",
    "HybridCandidate",
    "HybridRetrievalEvaluationResult",
    "HybridRetrievalResult",
    "IndexState",
    "IndexingReport",
    "IndexingStatus",
    "IngestionReport",
    "IngestionStatus",
    "LexicalCandidate",
    "LexicalIndexManifest",
    "LexicalIndexState",
    "LexicalIndexingReport",
    "LexicalRetrievalEvaluationResult",
    "LexicalRetrievalResult",
    "ParseWarning",
    "ParsedDocument",
    "ProvisioningStatus",
    "QueryTrace",
    "RetrievalCandidate",
    "RetrievalCaseResult",
    "RetrievalEvalCase",
    "RetrievalEvalDatasetMeta",
    "RetrievalResult",
    "SourceLocator",
    "WarningCategory",
]
