"""Code-owned Slice 8 generation semantic contracts."""

from __future__ import annotations

from offline_rag.core.ids import (
    FAKE_GENERATOR_CONTRACT,
    GROUNDED_ANSWER_V1,
    NO_RETRY_V1,
    OPENAI_COMPATIBLE_GENERATOR_V1,
    PROMPT_GROUNDED_V1,
    STRICT_LOCAL_ENDPOINT_V1,
)

ADAPTER_CONTRACT = OPENAI_COMPATIBLE_GENERATOR_V1
PROMPT_CONTRACT = PROMPT_GROUNDED_V1
OUTPUT_CONTRACT = GROUNDED_ANSWER_V1
RECOVERY_CONTRACT = NO_RETRY_V1
ENDPOINT_POLICY_CONTRACT = STRICT_LOCAL_ENDPOINT_V1
FAKE_CONTRACT = FAKE_GENERATOR_CONTRACT

EVIDENCE_BEGIN = "### BEGIN EVIDENCE"
EVIDENCE_END = "### END EVIDENCE"

PROBE_TIMEOUT_SECONDS = 3.0
